#!/bin/bash
# setup-testdata.sh - Creates test data structure for manual and automated testing

set -e # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Setting up test data...${NC}"

# Get the project root directory (parent of scripts/)
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Create directory structure
echo "Creating directory structure..."
mkdir -p "$PROJECT_ROOT/e2e/testdata/dotfiles/home/.config/nvim"
mkdir -p "$PROJECT_ROOT/e2e/testdata/dotfiles/private/home/.ssh"
mkdir -p "$PROJECT_ROOT/e2e/testdata/target"

# Create sample files
echo "Creating sample dotfiles..."
echo "# Test bashrc - generated by setup-testdata.sh" >"$PROJECT_ROOT/e2e/testdata/dotfiles/home/.bashrc"
echo "alias ll='ls -la'" >>"$PROJECT_ROOT/e2e/testdata/dotfiles/home/.bashrc"
echo "export EDITOR=vim" >>"$PROJECT_ROOT/e2e/testdata/dotfiles/home/.bashrc"

cat >"$PROJECT_ROOT/e2e/testdata/dotfiles/home/.gitconfig" <<EOF
[user]
  name = Test User
  email = test@example.com
[core]
  editor = vim
EOF

cat >"$PROJECT_ROOT/e2e/testdata/dotfiles/home/.config/nvim/init.vim" <<EOF
" Test vim config
set number
set autoindent
set expandtab
set tabstop=2
EOF

cat >"$PROJECT_ROOT/e2e/testdata/dotfiles/private/home/.ssh/config" <<EOF
Host test
  HostName example.com
  User testuser
  Port 22

Host *.test.local
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
EOF

# Create .gitkeep
touch "$PROJECT_ROOT/e2e/testdata/target/.gitkeep"

echo -e "${GREEN}✓ Test data setup complete!${NC}"
echo
echo "Test environment created at: $PROJECT_ROOT/e2e/testdata/"
echo
echo "You can now test lnk commands safely:"
echo "  cd e2e/testdata/dotfiles/home && lnk --target $PROJECT_ROOT/e2e/testdata/target status"
echo "  cd e2e/testdata/dotfiles/home && lnk --target $PROJECT_ROOT/e2e/testdata/target create"
echo "  cd e2e/testdata/dotfiles/home && lnk --target $PROJECT_ROOT/e2e/testdata/target remove"
echo
echo "To reset: rm -rf e2e/testdata/target/* && ./scripts/setup-testdata.sh"

